kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kcas-role
  labels:
    app: kcas
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kcas-rb
  labels:
    app: kcas
roleRef:
  kind: Role
  name: kcas-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: kcas