$patch: delete
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kcas-read
---
$patch: delete
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kcas-read-crb
