apiVersion: v1
kind: Service
metadata:
  labels:
    app: kcas
  name: kcas
  namespace: kcas-system
spec:
  ports:
  - name: "web"
    port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app: kcas
  type: ClusterIP
status:
  loadBalancer: {}
